name: Github Actions test
run-name: ${{ github.actor }} is testing Github Actions
# just some event that should not happen
on: [delete]
jobs:
	Explore-GitHub-Actions:
		runs-on: ubuntu-latest
		steps:
			- name: Test virtual display
				run: |
					export DISPLAY=:99
					sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
					sudo apt-get install -y python3-tk
					python -c 'import tkinter;r=tkinter.Tk();print(r.winfo_screenheight());print(r.winfo_screenwidth());'
			- run: echo "This job's status is ${{ job.status }}."
